name: photogenerator
description: exemple application

#flutter build apk
#get sha1: keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+10

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_config: ^2.0.2
  rxdart: ^0.27.7
  navigation_history_observer: ^1.1.0
  statusbarz: ^1.0.14
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  loader_overlay: ^3.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  responsive_sizer: ^3.1.1
  keyboard_utils: ^1.3.4
  easy_localization: ^3.0.1
  path_provider: ^2.1.2
  http: ^1.1.0
  platform_device_id: ^1.0.1
  flutter_secure_storage: ^8.0.0
  flutter_keychain: ^2.2.1
  connectivity_plus: ^4.0.1
  permission_handler: ^11.3.0
  google_mobile_ads: ^4.0.0
  uuid: ^4.3.3
  hex: ^0.2.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.10
  shimmer_animation: ^2.1.0+1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_inapp_purchase: ^5.6.1
  lottie: ^2.7.0
  animate_do: ^3.3.4
  flutter_animate: ^4.5.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0
  dio: ^5.4.1
  flutter_exif_rotation: ^0.5.1
  pinch_zoom: ^2.0.0
  share_plus: ^9.0.0
  preload_page_view: ^0.2.0
  provider: ^6.1.2
  image: ^4.2.0
  firebase_messaging: ^14.9.4

dev_dependencies:
  dependency_validator: ^3.2.2
  # flutter_native_splash: ^2.2.8

  flutter_test:
    sdk: flutter
  # flutter pub run dependency_validator
  # flutter pub run flutter_launcher_icons:main

# flutter_native_splash:
#   color: "#000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/translations/
    - assets/images/animated/
    - assets/images/logo/
    - assets/images/onboardings/
    - assets/images/others/
    # - assets/images/global/
    # - assets/images/no_user_page/
    # - assets/images/icon_vc/

  fonts:
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Regular.otf
        - asset: fonts/satoshi/Satoshi-Italic.otf
          style: italic
        - asset: fonts/satoshi/Satoshi-Black.otf
          weight: 900
        - asset: fonts/satoshi/Satoshi-BlackItalic.otf
          style: italic
          weight: 900
        - asset: fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/satoshi/Satoshi-BoldItalic.otf
          style: italic
          weight: 700
        - asset: fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/satoshi/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: fonts/satoshi/Satoshi-LightItalic.otf
          style: italic
          weight: 300
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
